# Generated by Django 4.2.5 on 2024-02-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lessee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complex", models.CharField(max_length=255)),
                ("num_contract", models.CharField(max_length=255)),
                ("data1", models.DateField(auto_now_add=True)),
                ("data2", models.DateField(auto_now_add=True)),
                ("data3", models.DateField(auto_now_add=True)),
                ("lessee", models.CharField(max_length=255)),
                ("lessor", models.CharField(max_length=255)),
                ("lessor_r_s", models.CharField(max_length=255)),
                ("type_contract", models.CharField(max_length=255)),
                ("comment", models.TextField()),
                ("num_document_in_count", models.CharField(max_length=255)),
                ("main_contract", models.CharField(max_length=255)),
                ("main_lot", models.IntegerField()),
            ],
        ),
    ]
