# Generated by Django 4.2.5 on 2024-02-09 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_lessee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessee",
            name="checbox1",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessee",
            name="checbox2",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessee",
            name="checbox3",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
