# Generated by Django 4.2.5 on 2024-02-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new_lessee", "0002_lessee_checbox1_lessee_checbox2_lessee_checbox3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complex", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Lessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lessor", models.CharField(max_length=255)),
                ("lessor_r_s", models.CharField(max_length=255)),
                ("type_contract", models.CharField(max_length=255)),
                ("num_contract", models.CharField(max_length=255)),
                ("data1", models.DateField(auto_now_add=True)),
                ("data2", models.DateField(auto_now_add=True)),
                ("data3", models.DateField(auto_now_add=True)),
                ("num_document_in_count", models.CharField(max_length=255)),
                ("main_contract", models.CharField(max_length=255)),
                ("main_lot", models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="checbox1",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="checbox2",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="checbox3",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="complex",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="data1",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="data2",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="data3",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="lessor",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="lessor_r_s",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="main_contract",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="main_lot",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="num_contract",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="num_document_in_count",
        ),
        migrations.RemoveField(
            model_name="lessee",
            name="type_contract",
        ),
    ]
