# Generated by Django 4.2.5 on 2024-02-02 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auth_reg", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="confirm_password",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="password",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="username",
        ),
    ]
